// <auto-generated />
using FirstCoreApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FirstCoreApp.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20200906152153_CreateIdentitySchema")]
    partial class CreateIdentitySchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FirstCoreApp.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "JK Rowling",
                            Description = "Nonumy mazim magna eum duis id dolore tempor vero eirmod sed dolor at aliquyam ullamcorper justo duo duo takimata labore amet nihil eos eirmod elitr sed eu augue nonumy elitr eu ut lorem eos velit ea facilisi lorem justo autem eu stet consectetuer justo et ea invidunt vero amet lorem",
                            Language = 0,
                            Title = "Harry Potter 1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Stephen King",
                            Description = "Iriure doming gubergren exerci tempor quis justo in nobis exerci diam iusto dolor labore velit takimata dolor invidunt dolor vel aliquyam rebum rebum dolor ea lorem ea lorem consequat diam nonumy vel clita invidunt dolore eirmod at voluptua invidunt at erat aliquyam accusam erat tempor consetetur eos autem congue luptatum",
                            Language = 3,
                            Title = "IT"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
